export const DESIGNATION_HIERARCHY: Record<string, { level: number; department: string }> = {
  "Chief Executive Officer (IAS)": { level: 1, department: "DISTRICT_ADMINISTRATION" },
  "Additional CEO": { level: 2, department: "DISTRICT_ADMINISTRATION" },
  "Project Director (DRDA)": { level: 3, department: "DISTRICT_ADMINISTRATION" },
  "District Mission Manager (MSRLM)": { level: 4, department: "DISTRICT_ADMINISTRATION" },
  "Agriculture Development Officer (ZP)": { level: 5, department: "AGRICULTURE" },
  "District Agriculture Officer (SCP)": { level: 6, department: "AGRICULTURE" },
  "District Agriculture Officer (General)": { level: 6, department: "AGRICULTURE" },
  "Agriculture Officer (AO)": { level: 7, department: "AGRICULTURE" },
  "Extension Officer (Agriculture)": { level: 8, department: "AGRICULTURE" },
  "District Social Welfare Officer (ZP)": { level: 5, department: "SOCIAL_WELFARE" },
  "Executive Engineer (Works/Construction)": { level: 5, department: "WORKS_CONSTRUCTION" },
  "Deputy Engineer (Works/Construction)": { level: 6, department: "WORKS_CONSTRUCTION" },
  "Section Engineer (Works)": { level: 7, department: "WORKS_CONSTRUCTION" },
  "Executive Engineer (Soil and Water Conservation)": { level: 5, department: "SOIL_WATER_CONSERVATION" },
  "Deputy Engineer (Soil and Water Conservation)": { level: 6, department: "SOIL_WATER_CONSERVATION" },
  "Executive Engineer Rural Water Supply": { level: 5, department: "RURAL_WATER_SUPPLY" },
  "Deputy Engineer (Water Supply)": { level: 6, department: "RURAL_WATER_SUPPLY" },
  "Section Engineer (Water Supply)": { level: 7, department: "RURAL_WATER_SUPPLY" },
  "District Health Officer": { level: 5, department: "HEALTH" },
  "Additional District Health Officer": { level: 6, department: "HEALTH" },
  "Taluka Medical Officer": { level: 7, department: "HEALTH" },
  "Medical Officer (MO)": { level: 8, department: "HEALTH" },
  "ANM": { level: 9, department: "HEALTH" },
  "Asha Worker": { level: 10, department: "HEALTH" },
  "Education Officer (Primary)": { level: 5, department: "EDUCATION_PRIMARY" },
  "Deputy Education Officer (Primary)": { level: 6, department: "EDUCATION_PRIMARY" },
  "Block Education Officer": { level: 7, department: "EDUCATION_PRIMARY" },
  "Cluster Head": { level: 8, department: "EDUCATION_PRIMARY" },
  "Headmaster": { level: 9, department: "EDUCATION_PRIMARY" },
  "Teacher": { level: 10, department: "EDUCATION_PRIMARY" },
  "Education Officer (Secondary)": { level: 5, department: "EDUCATION_SECONDARY" },
  "Deputy Education Officer (Secondary)": { level: 6, department: "EDUCATION_SECONDARY" },
  "Education Officer (Schemes)": { level: 5, department: "EDUCATION_SECONDARY" },
  "Chief Accounts and Finance Officer (CAFO)": { level: 5, department: "ACCOUNTS_FINANCE" },
  "Deputy Accounts and Finance Officer": { level: 6, department: "ACCOUNTS_FINANCE" },
  "Project Director (Water Supply and Sanitation)": { level: 5, department: "WATER_SUPPLY_SANITATION" },
  "Deputy Chief Executive Officer (Gram Panchayat)": { level: 4, department: "GRAM_PANCHAYAT" },
  "District Program Officer (Women and Child Development)": { level: 5, department: "WOMEN_CHILD_DEVELOPMENT" },
  "CDPO": { level: 6, department: "WOMEN_CHILD_DEVELOPMENT" },
  "Supervisor (WCD)": { level: 7, department: "WOMEN_CHILD_DEVELOPMENT" },
  "Anganwadi Worker": { level: 8, department: "WOMEN_CHILD_DEVELOPMENT" },
  "Deputy Chief Executive Officer (General Administration)": { level: 4, department: "GENERAL_ADMINISTRATION" },
  "Deputy Chief Executive Officer (NREGA)": { level: 4, department: "NREGA" },
}

export const DESIGNATIONS = Object.keys(DESIGNATION_HIERARCHY)

export const DEPARTMENTS = [
  "DISTRICT_ADMINISTRATION", "AGRICULTURE", "SOCIAL_WELFARE",
  "WORKS_CONSTRUCTION", "SOIL_WATER_CONSERVATION", "RURAL_WATER_SUPPLY",
  "HEALTH", "EDUCATION_PRIMARY", "EDUCATION_SECONDARY", "ACCOUNTS_FINANCE",
  "WATER_SUPPLY_SANITATION", "GRAM_PANCHAYAT", "WOMEN_CHILD_DEVELOPMENT",
  "GENERAL_ADMINISTRATION", "NREGA", "NONE"
] as const

export type DepartmentKey = typeof DEPARTMENTS[number]

export const DEPARTMENT_LABELS: Record<DepartmentKey, string> = {
  DISTRICT_ADMINISTRATION: "District Administration",
  AGRICULTURE: "Agriculture",
  SOCIAL_WELFARE: "Social Welfare",
  WORKS_CONSTRUCTION: "Works & Construction",
  SOIL_WATER_CONSERVATION: "Soil & Water Conservation",
  RURAL_WATER_SUPPLY: "Rural Water Supply",
  HEALTH: "Health",
  EDUCATION_PRIMARY: "Education (Primary)",
  EDUCATION_SECONDARY: "Education (Secondary)",
  ACCOUNTS_FINANCE: "Accounts & Finance",
  WATER_SUPPLY_SANITATION: "Water Supply & Sanitation",
  GRAM_PANCHAYAT: "Gram Panchayat",
  WOMEN_CHILD_DEVELOPMENT: "Women & Child Development",
  GENERAL_ADMINISTRATION: "General Administration",
  NREGA: "NREGA",
  NONE: "None",
}
